preprocessing:
  change_type_columns:
    ID: category
    Date: datetime64[ns]
  drop_columns: ['ID_Zindi', 'Date', 'NO2_trop', 'NO2_total'] 
  bins_columns: ['LST_bins', 'AAI_bins', 'CloudFraction_bins', 'TP_bins', 'NO2_strat_bins']
  list_median: ['CloudFraction', 'NO2_ratio', 'Sum_Concentration', 'TropopausePressure']
  list_mean: ['NO2_strat', 'LST', 'AAI']
  unique_values_path: ../data/processed/unique_values.json
  train_path: ../data/raw/train.csv
  geodata_path: ../data/geodata/Reg01012016/Reg01012016_WGS84.shp
  train_path_proc: ../data/processed/train.csv
  test_path_proc: ../data/processed/test.csv
  target_column: GT_NO2
  test_size: 0.25
  val_size: 0.16
  random_state: 10

train:
  n_trials: 15
  n_folds: 4
  random_state: 10
  target_column: GT_NO2
  params_path: ../report/best_params.json 
  model_path: ../models/model_lgbm.joblib
  study_path: ../models/study.joblib
  metrics_path: ../report/metrics.json

evaluate:
  predict_path: ../data/check/test.csv

endpoints:
  train: 'http://fastapi:8000/train'
  prediction_input: 'http://fastapi:8000/predict_input'
  prediction_from_file: 'http://fastapi:8000/predict'
#  train: 'http://localhost:8000/train'
#  prediction_input: 'http://localhost:8000/predict_input'
#  prediction_from_file: 'http://localhost:8000/predict'